#!/usr/bin/env python

# EULER 12
# 
# PROBLEM:
# 
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be:
#
	# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
#
# The first ten terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

# AUTHOR: jo
# DATE:   18-JUL-2011

# Very inefficient, but works. tested by setting numberOfDivisors = 6,
# returning triangle number 28.

# Need to ask mvx24 if there's a faster way of solving.

numberOfDivisors = 500	
initial = 0
while 1 > 0:
	divisorCount = 0
	initial += 1
	triangle = sum(xrange(initial))
	for i in range(1, triangle+1):
		if triangle % i == 0:
			divisorCount += 1

	if divisorCount < numberOfDivisors:
		continue
	else:
		if divisorCount >= numberOfDivisors:
			print "The triangle number is: %i" % triangle
			print "It has %i divisors\n" % divisorCount

			raw_input("Press any key to continue.")
			break